Task-1

In [ ]:
# convert units based on user choice
def convert_units():
    """Convert length, weight, or volume units."""
    try:
        print("Choose conversion type:")
        print("1. Length")
        print("2. Weight")
        print("3. Volume")

        choice = input("Enter your choice (1-3): ")
        value = float(input("Enter the value to convert: "))

        if choice == "1":
            print("Choose length conversion:")
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            option = input("Enter your choice (1-2): ")

            if option == "1":
                result = value * 3.28084
                print("Converted value:", result, "ft")
            elif option == "2":
                result = value / 3.28084
                print("Converted value:", result, "m")
            else:
                print("Invalid length option")

        elif choice == "2":
            print("Choose weight conversion:")
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            option = input("Enter your choice (1-2): ")

            if option == "1":
                result = value * 2.20462
                print("Converted value:", result, "lbs")
            elif option == "2":
                result = value / 2.20462
                print("Converted value:", result, "kg")
            else:
                print("Invalid weight option")

        elif choice == "3":
            print("Choose volume conversion:")
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            option = input("Enter your choice (1-2): ")

            if option == "1":
                result = value * 0.264172
                print("Converted value:", result, "gal")
            elif option == "2":
                result = value / 0.264172
                print("Converted value:", result, "L")
            else:
                print("Invalid volume option")

        else:
            print("Invalid conversion type")

    except ValueError:
        print("Please enter a numeric value only")


convert_units()

Choose conversion type:
1. Length
2. Weight
3. Volume
Enter your choice (1-3): 3
Enter the value to convert: 9
Choose volume conversion:
1. Liters to Gallons
2. Gallons to Liters
Enter your choice (1-2): 1
Converted value: 2.377548 gal


Task 2

In [ ]:
# return sum of numbers
def find_sum(numbers):
    """Return the sum of the list."""
    return sum(numbers)

# return average of numbers
def find_average(numbers):
    """Return the average of the list."""
    return sum(numbers) / len(numbers)

# return largest number
def find_maximum(numbers):
    """Return the maximum value."""
    return max(numbers)

# return smallest number
def find_minimum(numbers):
    """Return the minimum value."""
    return min(numbers)


try:
    user_input = input("Enter numbers separated by spaces: ")
    numbers = list(map(float, user_input.split()))

    if len(numbers) == 0:
        print("The list is empty")
    else:
        print("Choose operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")

        choice = input("Enter your choice (1-4): ")

        if choice == "1":
            print("Sum =", find_sum(numbers))
        elif choice == "2":
            print("Average =", find_average(numbers))
        elif choice == "3":
            print("Maximum =", find_maximum(numbers))
        elif choice == "4":
            print("Minimum =", find_minimum(numbers))
        else:
            print("Invalid operation")

except ValueError:
    print("Please enter valid numbers only")

Enter numbers separated by spaces: 1
Choose operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 1
Sum = 1.0


 Exercise on List Manipulation

Extract Every Other Element

In [ ]:
# return every other element from the list
def extract_every_other(lst):
    return lst[::2]

print(extract_every_other([1, 2, 3, 4, 5, 6]))

[1, 3, 5]


Slice a Sublist

In [ ]:
# return sublist from start to end inclusive
def get_sublist(lst, start, end):
    return lst[start:end+1]

print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))

[3, 4, 5]


Reverse a List Using Slicing

In [ ]:
# reverse list using slicing
def reverse_list(lst):
    return lst[::-1]

print(reverse_list([1, 2, 3, 4, 5]))


[5, 4, 3, 2, 1]


Remove the First and Last Elements

In [ ]:
# remove first and last elements
def remove_first_last(lst):
    return lst[1:-1]

print(remove_first_last([1, 2, 3, 4, 5]))

[2, 3, 4]


Get the First n Elements

In [ ]:
# return first n elements
def get_first_n(lst, n):
    return lst[:n]

print(get_first_n([1, 2, 3, 4, 5], 3))

[1, 2, 3]


Extract Elements from the End

In [ ]:
# return last n elements
def get_last_n(lst, n):
    return lst[-n:]

print(get_last_n([1, 2, 3, 4, 5], 2))

[4, 5]


Extract Elements in Reverse Order

In [ ]:
# return elements in reverse order by skipping one
def reverse_skip(lst):
    return lst[-2::-2]

print(reverse_skip([1, 2, 3, 4, 5, 6]))

[5, 3, 1]


 Exercise on Nested List

Flatten a Nested List

In [ ]:
# flatten one-level nested list
def flatten(lst):
    result = []
    for sublist in lst:
        result.extend(sublist)
    return result

print(flatten([[1, 2], [3, 4], [5]]))

[1, 2, 3, 4, 5]


Accessing Nested List Elements

In [ ]:
# access an element using given indices
def access_nested_element(lst, indices):
    value = lst
    for index in indices:
        value = value[index]
    return value

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(access_nested_element(lst, [1, 2]))

6


Sum of All Elements in a Nested List

In [ ]:
# find sum of all nested elements
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

print(sum_nested([[1, 2], [3, [4, 5]], 6]))

21


Remove Specific Element from a Nested List

In [ ]:
# remove all occurrences of elem from nested list
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            cleaned = remove_element(item, elem)
            result.append(cleaned)
        else:
            if item != elem:
                result.append(item)
    return result

print(remove_element([[1, 2], [3, 2], [4, 5]], 2))

[[1], [3], [4, 5]]


Find the Maximum Element in a Nested List

In [ ]:
# find maximum element in nested list
def find_max(lst):
    max_value = float("-inf")
    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))
        else:
            max_value = max(max_value, item)
    return max_value

print(find_max([[1, 2], [3, [4, 5]], 6]))

6


Count Occurrences of an Element in a Nested List

In [ ]:
# count occurrences of elem in nested list
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count

print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))

3


Flatten a List of Lists of Lists

In [ ]:
# deeply flatten nested list
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


Nested List Average

In [ ]:
# find average of all nested elements
def average_nested(lst):
    flat_list = deep_flatten(lst)
    return sum(flat_list) / len(flat_list)

print(average_nested([[1, 2], [3, 4], [5, 6]]))

3.5


Basic Vector and Matrix Operation with NumPy

Array Creation

In [ ]:
import numpy as np

# 1. create empty 2x2 array
arr1 = np.empty((2, 2))
print("1.\n", arr1)

# 2. create all ones 4x2 array
arr2 = np.ones((4, 2))
print("2.\n", arr2)

# 3. create full array with given value
arr3 = np.full((3, 3), 7)
print("3.\n", arr3)

# 4. create zeros array like given array
base_array = np.array([[1, 2], [3, 4]])
arr4 = np.zeros_like(base_array)
print("4.\n", arr4)

# 5. create ones array like given array
arr5 = np.ones_like(base_array)
print("5.\n", arr5)

# 6. convert list to numpy array
new_list = [1, 2, 3, 4]
arr6 = np.array(new_list)
print("6.\n", arr6)

1.
 [[1.46764581e-315 0.00000000e+000]
 [6.56199575e-310 6.56199573e-310]]
2.
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
3.
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
4.
 [[0 0]
 [0 0]]
5.
 [[1 1]
 [1 1]]
6.
 [1 2 3 4]


Array Manipulation

In [ ]:
import numpy as np

# 1. create array from 10 to 49
a1 = np.arange(10, 50)
print("1.\n", a1)

# 2. create 3x3 matrix from 0 to 8
a2 = np.arange(9).reshape(3, 3)
print("2.\n", a2)

# 3. create 3x3 identity matrix
a3 = np.eye(3)
print("3.\n", a3)

# 4. create random array of size 30 and find mean
a4 = np.random.random(30)
print("4.\n", a4)
print("Mean =", a4.mean())

# 5. create 10x10 random array and find min and max
a5 = np.random.random((10, 10))
print("5.\n", a5)
print("Minimum =", a5.min())
print("Maximum =", a5.max())

# 6. create zero array and replace 5th element with 1
a6 = np.zeros(10)
a6[4] = 1
print("6.\n", a6)

# 7. reverse given array
arr = np.array([1, 2, 0, 0, 4, 0])
a7 = arr[::-1]
print("7.\n", a7)

# 8. create 2D array with border 1 and inside 0
a8 = np.ones((5, 5))
a8[1:-1, 1:-1] = 0
print("8.\n", a8)

# 9. create checkerboard pattern
a9 = np.zeros((8, 8), dtype=int)
a9[1::2, ::2] = 1
a9[::2, 1::2] = 1
print("9.\n", a9)

1.
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
2.
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
3.
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4.
 [0.83183277 0.57309198 0.97190597 0.69283784 0.4041534  0.94546922
 0.84098373 0.04480766 0.40032457 0.43203335 0.39337731 0.62314187
 0.90955512 0.11736373 0.35405314 0.37041304 0.53988343 0.71255232
 0.92250964 0.17014569 0.40968033 0.63316942 0.19254516 0.4378727
 0.45580217 0.26554253 0.67208687 0.89216238 0.05050807 0.53937445]
Mean = 0.5266393287529403
5.
 [[0.97651239 0.95626657 0.55334566 0.00121242 0.66372914 0.19022911
  0.39390954 0.25265593 0.27024411 0.5494541 ]
 [0.78341917 0.84650693 0.9842973  0.80717841 0.6317544  0.47096124
  0.50032506 0.74277057 0.37860723 0.69812961]
 [0.5183679  0.71084382 0.78574231 0.95060927 0.0192672  0.90970637
  0.42889692 0.47701192 0.40727261 0.09426692]
 [0.76627879 0.3053721  0.5384118  0.15774918 0.77761499 0.73248157
  0.49867752 0.393

Array Operations

In [ ]:
import numpy as np

# define given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. add two arrays
print("1.\n", x + y)

# 2. subtract two arrays
print("2.\n", x - y)

# 3. multiply arrays by an integer
print("3.\n", x * 2)
print(v * 3)

# 4. square each element
print("4.\n", np.square(x))
print(np.square(v))

# 5. dot products
print("5a.\n", np.dot(v, w))
print("5b.\n", np.dot(x, v))
print("5c.\n", np.dot(x, y))

# 6. concatenate x and y by rows, v and w by columns
print("6a.\n", np.concatenate((x, y), axis=0))
print("6b.\n", np.column_stack((v, w)))

# 7. concatenate x and v and explain error
try:
    print(np.concatenate((x, v), axis=0))
except ValueError as e:
    print("7.\nError:", e)
    print("Reason: x is 2D and v is 1D, so dimensions do not match.")

1.
 [[ 6  8]
 [10 13]]
2.
 [[-4 -4]
 [-4 -3]]
3.
 [[ 2  4]
 [ 6 10]]
[27 30]
4.
 [[ 1  4]
 [ 9 25]]
[ 81 100]
5a.
 219
5b.
 [29 77]
5c.
 [[19 22]
 [50 58]]
6a.
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b.
 [[ 9 11]
 [10 12]]
7.
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x is 2D and v is 1D, so dimensions do not match.


Matrix Operations

In [ ]:
import numpy as np

# define matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. prove A.A^-1 = I
A_inv = np.linalg.inv(A)
identity_result = np.dot(A, A_inv)
print("1.\n", identity_result)

# 2. prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("2. AB =\n", AB)
print("2. BA =\n", BA)

# 3. prove (AB)^T = B^T A^T
left_side = (np.dot(A, B)).T
right_side = np.dot(B.T, A.T)
print("3. (AB)^T =\n", left_side)
print("3. B^T A^T =\n", right_side)

# represent system of equations
coeff = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

const = np.array([-1, -3, 9])

# solve using inverse method
solution = np.dot(np.linalg.inv(coeff), const)
print("Solution using inverse method =", solution)

# solve using np.linalg.inv directly
inv_coeff = np.linalg.inv(coeff)
solution2 = np.dot(inv_coeff, const)
print("Solution using np.linalg.inv =", solution2)

1.
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
2. AB =
 [[23 13]
 [51 29]]
2. BA =
 [[36 44]
 [13 16]]
3. (AB)^T =
 [[23 51]
 [13 29]]
3. B^T A^T =
 [[23 51]
 [13 29]]
Solution using inverse method = [ 2.  1. -2.]
Solution using np.linalg.inv = [ 2.  1. -2.]


Experiment: How Fast is NumPy?

In [ ]:
import time
import numpy as np

# create large Python lists
list1 = list(range(1000000))
list2 = list(range(1000000))

# create large NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

# 1. element-wise addition using Python lists
start = time.time()
list_add = [list1[i] + list2[i] for i in range(len(list1))]
end = time.time()
print("Python list addition time:", end - start, "seconds")

# 1. element-wise addition using NumPy
start = time.time()
arr_add = arr1 + arr2
end = time.time()
print("NumPy addition time:", end - start, "seconds")

# 2. element-wise multiplication using Python lists
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(len(list1))]
end = time.time()
print("Python list multiplication time:", end - start, "seconds")

# 2. element-wise multiplication using NumPy
start = time.time()
arr_mul = arr1 * arr2
end = time.time()
print("NumPy multiplication time:", end - start, "seconds")

# 3. dot product using Python lists
start = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(len(list1)))
end = time.time()
print("Python list dot product time:", end - start, "seconds")

# 3. dot product using NumPy
start = time.time()
dot_arr = np.dot(arr1, arr2)
end = time.time()
print("NumPy dot product time:", end - start, "seconds")

Python list addition time: 0.10683202743530273 seconds
NumPy addition time: 0.005109310150146484 seconds
Python list multiplication time: 0.12341833114624023 seconds
NumPy multiplication time: 0.004873037338256836 seconds
Python list dot product time: 0.10239005088806152 seconds
NumPy dot product time: 0.0018932819366455078 seconds


Experiment – Matrix Multiplication Speed

In [ ]:
import time
import numpy as np
import random

# smaller size so Python loops finish
size = 200

# create matrices using Python lists
matrix1 = [[random.random() for _ in range(size)] for _ in range(size)]
matrix2 = [[random.random() for _ in range(size)] for _ in range(size)]

# Python list matrix multiplication
start = time.time()

result_list = [[0 for _ in range(size)] for _ in range(size)]

for i in range(size):
    for j in range(size):
        for k in range(size):
            result_list[i][j] += matrix1[i][k] * matrix2[k][j]

end = time.time()

print("Python list multiplication time:", end - start, "seconds")


# NumPy matrix multiplication
arr1 = np.array(matrix1)
arr2 = np.array(matrix2)

start = time.time()

result_numpy = np.dot(arr1, arr2)

end = time.time()

print("NumPy multiplication time:", end - start, "seconds")

Python list multiplication time: 3.6736433506011963 seconds
NumPy multiplication time: 0.0013477802276611328 seconds
